language: python
python:
  - "3.6"
services:
  - postgresql
addons:
  postgresql: "9.5"
install:
  - pip install -r requirements.txt
script:
  - DB_TEST_URL=postgres://postgres:@localhost:5432/ pytest pgmerge
