type: //map
values:
  type: //rec
  optional:
    columns: 
        type: //arr
        length: { min: 1 }
        contents: { type: //str }
    pk:
        type: //arr
        length: { min: 1 }
        contents: { type: //str }
