type: //map
values:
  type: //rec
  optional:
    columns: 
        type: //arr
        length: { min: 1 }
        contents: { type: //str }
    alternate_key:
        type: //arr
        length: { min: 1 }
        contents: { type: //str }
    where: //str
    subsets:
        type: //arr
        length: { min: 1 }
        contents:
            type: //rec
            required:
                name: //str
                where: //str
            optional:
                columns: 
                    type: //arr
                    length: { min: 1 }
                    contents: { type: //str }
                # TODO: Alternate keys have to be per table, but subsets can set defaults?
                # (replace or add 'default' to 'where'?)
                #alternate_key_defaults:
                #    type: //arr
                #    length: { min: 1 }
                #    contents: { type: //str }
